#!/usr/bin/env bash
#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  - z0mbi3
#  ╠╩╗╚═╗╠═╝║║║║║║  - https://github.com/gh0stzk/dotfiles
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  - z0mbi3.zk@protonmail.com

# ##############################################################################
# #                                  ENV VARS                                  #
# ##############################################################################
## Environments
export PATH="${PATH}:${HOME}/.config/bspwm/bin"
PATH="$HOME/.config/bspwm/scripts:$PATH"
SCRIPTS="$HOME/.config/bspwm/scripts"

# Parse colors from "~/.Xresources"
xrdb -override "${HOME}/.Xresources"

xrdb_query()
{
    [ -n "$XRDB_QUERY" ] || XRDB_QUERY="$(xrdb -query)"

    echo "$XRDB_QUERY" | while IFS=';' read -r STRING; do
        [ "${1}" = "${STRING%%\	*}" ] || continue
        echo "${STRING##*\	}"
        break
    done
}

getcolors()
{
    #FOREGROUND="$(xrdb_query '*.foreground:')"
    BACKGROUND="$(xrdb_query '*.background:')"
    #BLACK="$(xrdb_query '*.color0:')"
    #RED="$(xrdb_query '*.color1:')"
    #GREEN="$(xrdb_query '*.color2:')"
    #YELLOW="$(xrdb_query '*.color3:')"
    #BLUE="$(xrdb_query '*.color4:')"
    #MAGENTA="$(xrdb_query '*.color5:')"
    #CYAN="$(xrdb_query '*.color6:')"
    #WHITE="$(xrdb_query '*.color7:')"
}

getcolors

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################
# Set system vars for polybar
#. SetSysVars
# Terminate already running polybar, eww, picom, sxhkd and dunst instances
# processes=("picom" "polybar" "eww" "sxhkd" "dunst")

# for process in "${processes[@]}"; do
#   if pidof -q "$process"; then
#     pkill -9 -x "$process" > /dev/null; sleep 0.0;9u1
#   fi
# done

# Load colors, dunst, bars and/or eww widgets
#. ${rice_dir}/Theme.sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.local/bin/eww -c $HOME/.config/eww --restart open bar &
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &

# Launch polkit
[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &
#pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

xfce4-power-manager &
[ -n "$(pidof mpd)" ] || mpd &

sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &
# bspfloat & # currently @bottom
feh -z --no-fehbg --bg-fill $HOME/Pictures/wallpapers/

# Fix cursor
xsetroot -cursor_name left_ptr

# ##############################################################################
# #                            CORE CONFIGURATION                              #
# ##############################################################################
# Monitors
xrandr --auto
xrandr --output DP-0 --primary --mode 2560x1440 --rate 144
xrandr --output HDMI-0 --mode 1680x1050 --left-of DP-0
monitors=$(bspc query -M --names)
monitor_left=${monitors[0]}
monitor_right=${monitors[1]}

# Set main monitor
bspc monitor ${monitor_right} -s ${monitor_left}
sleep 0.01

# Workspaces
bspc monitor "$monitor_right" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10'
bspc monitor "$monitor_left" -d '11' '12'

. WindowRules


# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################
#bspc config external_rules_command $HOME/.config/bspwm/scripts/ExternalRules


bspc config split_ratio                   0.51
bspc config single_monocle                true
bspc config borderless_monocle            false
bspc config gapless_monocle               false

bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         true
bspc config pointer_motion_interval       5
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

#bspc wm --adopt-orphans
#bspc rule -a scratch sticky=on state=floating focus=on

# Make space for bar
config top_padding 2

bspc config -m 2 top_padding 46
bspc config -m 2 bottom_padding 2
bspc config -m 2 left_padding 2
bspc config -m 2 right_padding 2

bspc config -m 1 top_padding 2
bspc config -m 1 bottom_padding 2
bspc config -m 1 left_padding 2
bspc config -m 1 right_padding 2

config border_width 2
config window_gap 2
config split_ratio 0.50

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

bspc config normal_border_color "#15060e"
bspc config focused_border_color "#590133"
config presel_feedback_color "$BACKGROUND"
pkill borders ; borders &

# Keyboard layout
setxkbmap -layout us -variant altgr-intl

# Start bspwm scripts
autostart
stcolors
bspcolors
bspcomp
bspdunst
bspbar
bspfloat

# Other software
ulauncher &
