require("baron.plugins-setup")

-- \_core
require("baron.core.options")
require("baron.core.keymaps")
require("baron.core.colorscheme")

-- \_plugins
require("baron.plugins.autopairs")
require("baron.plugins.coc")
require("baron.plugins.comment")
require("baron.plugins.emmet")
require("baron.plugins.fugitive")
require("baron.plugins.gitsigns")
require("baron.plugins.harpoon")
-- require("baron.plugins.lspzero")
require("baron.plugins.lualine")
require("baron.plugins.minimap")
require("baron.plugins.nvim-cmp")
require("baron.plugins.nvim-tree")
require("baron.plugins.prettier")
require("baron.plugins.rust")
require("baron.plugins.telescope")
require("baron.plugins.treesitter")
require("baron.plugins.undotree")
-- ->\_lsp
-- require("baron.plugins.lsp.mason")
-- require("baron.plugins.lsp.lspsaga")
-- require("baron.plugins.lsp.lspconfig")
-- require("baron.plugins.lsp.null-ls")
